/**
 * Workflow pattern catalog and embedded scaffolds for dynamic-workflows.
 *
 * Keep these templates self-contained in the package so runtime template lookup does
 * not depend on examples/ or any project-local files being present.
 */

export const WORKFLOW_TEMPLATE = [
	"/**",
	" * Pi Dynamic Workflow",
	" *",
	" * Export a function: async function workflow(ctx, input) { ... }",
	" *",
	" * Pattern defaults:",
	" * - Scout first, then choose fan-out dynamically from the discovered work-list.",
	" * - Raise concurrency/maxAgents for many independent, read-only, low-risk items; keep them low for side effects, expensive models, shared-state edits, rate limits, or sequential dependencies.",
	" * - Decide model + thinking per call: cheap/fast model + low thinking for wide scouts/classification; stronger model + high/xhigh thinking for synthesis, verification, and hard reasoning. Pass { model, provider, thinking } on agent/agents/pipeline/specs.",
	" * - Log the selected concurrency/maxAgents and any ctx.limits clamp so caps are visible.",
	" * - Use evidence contracts and synthesis-as-judge; do not summarize unsupported claims.",
	" * - Subagents get web_search via pi-codex-web-search and context7-cli when installed; do not opt out unless isolation is required.",
	" * - Log caps and partial failures; never hide skipped work.",
	" *",
	" * Useful ctx helpers:",
	" * - ctx.agent(prompt, opts)        Run one Pi subagent; opts can include model, provider, thinking (off|minimal|low|medium|high|xhigh), tools, skills, extensions, keys, schema, or agentType",
	" * - ctx.agents([...], opts)        Run many subagents with bounded concurrency; add {settle:true} for null-on-failure",
	" * - ctx.pipeline(items, ...stages) Multi-stage per-item flow without global barriers; failed items return null",
	" * - ctx.parallel([...thunks])      Run async branches with a barrier; failed branches return null",
	" * - ctx.workflow(name, input)      Compose a reusable sub-workflow inline (depth 1, shared run budget/cache)",
	" * - ctx.bash(command, opts)        Run a shell command",
	" * - ctx.readFile/writeFile(...)    File helpers relative to the project cwd",
	" * - ctx.writeArtifact(name, data)  Persist intermediate state under ctx.runDir",
	" * - ctx.log(message, details)      Stream progress to Pi and events.jsonl",
	" */",
	"",
	"function chooseConcurrency(ctx, input, items, opts = {}) {",
	"  if (Number.isFinite(input?.concurrency)) {",
	"    return Math.min(Math.max(Math.floor(input.concurrency), 1), ctx.limits.concurrency, Math.max(1, items.length));",
	"  }",
	"  if (items.length <= 1) return 1;",
	"  if (opts.sideEffects || opts.expensiveModel || opts.sharedState) return Math.min(2, items.length, ctx.limits.concurrency);",
	"  if (opts.readOnlyAudit && items.length >= 50) return Math.min(12, items.length, ctx.limits.concurrency);",
	"  if (opts.readOnlyAudit && items.length >= 20) return Math.min(8, items.length, ctx.limits.concurrency);",
	"  if (items.length >= 8 && !opts.expensiveModel) return Math.min(6, items.length, ctx.limits.concurrency);",
	"  return Math.min(4, items.length, ctx.limits.concurrency); // small/safe fallback, not a default ceiling",
	"}",
	"",
	"module.exports = async function workflow(ctx, input) {",
	"  await ctx.log(\"Starting workflow\", { input });",
	"",
	"  const files = await ctx.bash(\"git ls-files\", { throwOnError: true });",
	"  const allCandidates = files.stdout",
	"    .split(\"\\n\")",
	"    .filter(Boolean)",
	"    .filter((file) => /\\.(ts|tsx|js|jsx|py|go|rs)$/.test(file));",
	"  const limit = input?.limit ?? 12;",
	"  const candidates = allCandidates.slice(0, limit);",
	"  if (candidates.length < allCandidates.length) {",
	"    await ctx.log(\"candidate cap applied\", { reviewed: candidates.length, total: allCandidates.length, skipped: allCandidates.length - candidates.length });",
	"  }",
	"  await ctx.writeArtifact(\"candidate-files.json\", candidates);",
	"",
	"  const concurrency = chooseConcurrency(ctx, input, candidates, { readOnlyAudit: true });",
	"  await ctx.log(\"fan-out selected\", { items: candidates.length, concurrency, maxAgents: ctx.limits.maxAgents });",
	"",
	"  // Per-call model/thinking: wide scouts can run cheaper + lower thinking; the",
	"  // synthesis below runs higher thinking. Uncomment `model` to pin a model id.",
	"  const reviews = await ctx.agents(",
	"    candidates.map((file, index) => ({",
	"      name: `review-${file}`,",
	"      prompt: `Review ${file} for likely bugs or risky code. This is branch ${index + 1}/${candidates.length}; your report must be useful even if other branches fail. Cite file/line evidence for every finding. Say NO_FINDINGS if there are no credible issues.`,",
	"      tools: [\"read\", \"grep\", \"find\", \"ls\"],",
	"      agentType: \"reviewer\",",
	"      // model: \"haiku\", // optional: a cheaper/faster model for wide scouting",
	"      thinking: \"low\", // cheap per-file pass; explicit thinking overrides the persona default",
	"    })),",
	"    { concurrency, settle: true },",
	"  );",
	"  const completedReviews = reviews.filter(Boolean);",
	"  await ctx.log(\"fan-out complete\", { total: reviews.length, completed: completedReviews.length, failed: reviews.length - completedReviews.length });",
	"",
	"  await ctx.writeArtifact(\"reviews.json\", reviews);",
	"",
	"  const synthesis = await ctx.agent(",
	"    `Synthesize these review outputs into prioritized findings. Pattern: synthesis-as-judge. Discard unsupported claims; mention caps and failed branches.\\n\\nCoverage: ${candidates.length}/${allCandidates.length} files, failed branches: ${reviews.length - completedReviews.length}\\n\\n${ctx.compact(completedReviews, 50000)}`,",
	"    // Stronger reasoning for the judge step; pin a model with `model` if you want.",
	"    { name: \"synthesis\", tools: [\"read\", \"grep\", \"find\", \"ls\"], agentType: \"reviewer\", thinking: \"high\" },",
	"  );",
	"",
	"  await ctx.writeArtifact(\"summary.md\", synthesis.output);",
	"  return synthesis.output;",
	"};",
	"",
].join("\n");

export interface WorkflowPattern {
	key: string;
	title: string;
	blurb: string;
	useWhen: string;
	inputHint: string;
	primitives: string[];
	defaultName: string;
	category?: "template" | "compose" | "use-case";
	useCases?: string[];
}

export const WORKFLOW_PATTERN_CATALOG: WorkflowPattern[] = [
	{
		key: "classify-and-act",
		title: "Classify and act",
		category: "template",
		blurb: "Scout/classify items cheaply, then run targeted follow-ups only for high-signal classes.",
		useWhen: "Many items need different handling after a cheap classifier, such as code audits or migrations.",
		inputHint: "{ \"pattern\": \"\\\\.(ts|tsx|js)$\", \"maxFiles\": 40 }",
		primitives: ["ctx.bash", "ctx.pipeline", "ctx.agent(schema)"],
		defaultName: "classify-and-act",
	},
	{
		key: "fan-out-and-synthesize",
		title: "Fan-out and synthesize",
		category: "template",
		blurb: "Split independent work across agents, then synthesize as a judge with evidence and partial-failure notes.",
		useWhen: "The task has many independent branches and a final merge/synthesis step.",
		inputHint: "{ \"limit\": 12, \"concurrency\": 4 }",
		primitives: ["ctx.bash", "ctx.agents(settle)", "ctx.agent"],
		defaultName: "fan-out-and-synthesize",
	},
	{
		key: "adversarial-verification",
		title: "Adversarial verification",
		category: "template",
		blurb: "Launch skeptics per claim/finding and keep only what survives evidence-backed refutation.",
		useWhen: "You have findings, claims, or plans and need confidence before acting on them.",
		inputHint: "{ \"findings\": [{ \"id\": \"f1\", \"claim\": \"...\" }], \"skeptics\": 3 }",
		primitives: ["ctx.parallel", "ctx.agent(schema)", "voting"],
		defaultName: "adversarial-verification",
	},
	{
		key: "generate-and-filter",
		title: "Generate and filter",
		category: "template",
		blurb: "Generate candidates from distinct angles, judge by rubric, and escalate only if confidence is low.",
		useWhen: "You need best-of-N options without trusting one sample or one scalar score.",
		inputHint: "{ \"question\": \"...\", \"angles\": [\"risk-first\", \"simplicity-first\"] }",
		primitives: ["ctx.parallel", "ctx.agent(schema)", "adaptive loop"],
		defaultName: "generate-and-filter",
	},
	{
		key: "tournaments",
		title: "Tournaments",
		category: "template",
		blurb: "Generate or accept candidates and run pairwise judging rounds until one winner remains.",
		useWhen: "You need comparative ranking, not just independent scoring.",
		inputHint: "{ \"topic\": \"...\", \"angles\": [\"cost\", \"quality\", \"risk\"] }",
		primitives: ["ctx.agents(settle)", "ctx.agent(schema)", "bracket"],
		defaultName: "tournaments",
	},
	{
		key: "loop-until-done",
		title: "Loop until done",
		category: "template",
		blurb: "Repeat discovery or repair rounds until no new findings remain or a hard stop condition fires.",
		useWhen: "The work-list size is unknown and progress should stop on quiet rounds, max rounds, budget, or timeout.",
		inputHint: "{ \"finders\": 3, \"quietRounds\": 2, \"maxRounds\": 8 }",
		primitives: ["ctx.agents(settle)", "loop", "ctx.log"],
		defaultName: "loop-until-done",
	},
	{
		key: "compose-verify-claims",
		title: "Compose: verify claims",
		category: "compose",
		blurb: "Discover claims/items, then delegate reusable verification to ctx.workflow('lib/verify-claims').",
		useWhen: "Discovery and reusable verification can run in one parent workflow without a decision gate between them.",
		inputHint: "{ \"topic\": \"claims to discover and verify\" }",
		primitives: ["ctx.workflow", "ctx.agent", "sub-workflow"],
		defaultName: "compose-verify-claims",
	},
	{
		key: "lib-verify-claims",
		title: "Lib: verify claims",
		category: "compose",
		blurb: "Reusable sub-workflow contract: { claims, skeptics? } -> verified/dropped claims with evidence.",
		useWhen: "You want a shared library workflow under lib/ that parent workflows call with ctx.workflow().",
		inputHint: "{ \"claims\": [{ \"id\": \"c1\", \"claim\": \"...\" }] }",
		primitives: ["ctx.agents(settle)", "ctx.agent(schema)", "library contract"],
		defaultName: "lib/verify-claims",
	},
	{
		key: "workflow-factory",
		title: "Workflow factory",
		category: "compose",
		blurb: "Meta-workflow that designs prompts/contracts, generates a task-specific draft, and reviews it.",
		useWhen: "A warranted workflow needs complex prompt/contract design before spending many subagents.",
		inputHint: "{ \"task\": \"audit this repo for race conditions\", \"write\": true }",
		primitives: ["ctx.agent(schema)", "prompt improvement", "ctx.writeFile"],
		defaultName: "workflow-factory",
	},
	{
		key: "bug-hunt-repo-audit",
		title: "Bug hunt / repo audit",
		category: "use-case",
		blurb: "Scout code files, fan out reviewer agents, and synthesize prioritized bugs with citations.",
		useWhen: "You want a reusable broad bug-hunt workflow rather than a one-off generated audit.",
		inputHint: "{ \"maxFiles\": 40, \"concurrency\": 4 }",
		primitives: ["ctx.bash", "ctx.agents(settle)", "reviewer synthesis"],
		defaultName: "bug-hunt-repo-audit",
	},
	{
		key: "large-migration",
		title: "Large migration",
		category: "use-case",
		blurb: "Scout and classify files, then target migration review/work only where the classifier says it matters.",
		useWhen: "A migration spans many files and needs capped, evidence-backed coverage before implementation.",
		inputHint: "{ \"pattern\": \"\\\\.(ts|tsx|js)$\", \"maxFiles\": 80 }",
		primitives: ["ctx.bash", "ctx.pipeline", "ctx.agent(schema)"],
		defaultName: "large-migration",
	},
	{
		key: "complex-research",
		title: "Complex research",
		category: "use-case",
		blurb: "Run independent research angles, then synthesize with citations/evidence and coverage notes.",
		useWhen: "You need broad source-backed research, migration analysis, or vendor/architecture comparison.",
		inputHint: "{ \"question\": \"...\", \"angles\": [\"docs\", \"risks\", \"alternatives\"] }",
		primitives: ["ctx.agents(settle)", "research angles", "synthesis-as-judge"],
		defaultName: "complex-research",
	},
	{
		key: "plan-review",
		title: "Plan review",
		category: "use-case",
		blurb: "Review a plan from multiple skeptical perspectives and synthesize accepted risks and fixes.",
		useWhen: "Before implementing a risky plan, migration, or architecture change.",
		inputHint: "{ \"plan\": \"...\", \"perspectives\": [\"security\", \"performance\"] }",
		primitives: ["ctx.agents(settle)", "reviewer panel", "synthesis-as-judge"],
		defaultName: "plan-review",
	},
	{
		key: "claim-bug-verification",
		title: "Claim/bug verification",
		category: "use-case",
		blurb: "Verify suspected bugs or factual claims with independent skeptics before reporting or acting.",
		useWhen: "A previous sweep produced claims/findings that need evidence-backed pruning.",
		inputHint: "{ \"findings\": [{ \"id\": \"f1\", \"claim\": \"...\" }], \"skeptics\": 3 }",
		primitives: ["ctx.parallel", "ctx.agent(schema)", "voting"],
		defaultName: "claim-bug-verification",
	},
];

const WORKFLOW_PATTERN_USE_CASES: Record<string, string[]> = {
	"classify-and-act": ["Audit only files that a cheap classifier marks medium/high risk", "Review a PR by touched files with deeper follow-up only where needed", "Migrate a codebase by classifying files before targeted action"],
	"fan-out-and-synthesize": ["Split a docs audit by file and synthesize", "Run independent reviewers over a capped work-list", "Prototype a one-off generated workflow under <slug>"],
	"adversarial-verification": ["Verify suspected bugs before filing them", "Have skeptics refute a migration plan", "Drop hallucinated findings from a previous broad sweep"],
	"generate-and-filter": ["Generate several implementation strategies and keep the best", "Pick between architecture options by rubric", "Improve a prompt by trying variants and judging confidence"],
	tournaments: ["Rank candidate designs pairwise", "Choose the best generated prompt/template", "Compare multiple remediation plans without relying on one scalar score"],
	"loop-until-done": ["Keep searching for security issues until quiet rounds", "Discover unknown call sites or migration blockers", "Run repair/verify rounds until green or capped"],
	"compose-verify-claims": ["Use ctx.workflow('lib/verify-claims') as a reusable verification phase", "Separate discovery from reusable claim verification", "Demonstrate parent/child workflow composition"],
	"lib-verify-claims": ["Reusable sub-workflow for fact-checking claims", "Shared verifier called by multiple generated workflows", "Teach lib/ convention for composable workflow building blocks"],
	"workflow-factory": ["Given a user task, design a custom <slug> workflow", "Improve prompts/contracts before spending many subagents", "Produce a reusable workflow scaffold plus review notes as artifacts"],
	"bug-hunt-repo-audit": ["Find likely bugs across many repo files", "Run reviewer agents by file chunk", "Produce prioritized findings with citations"],
	"large-migration": ["Classify migration files by risk", "Find migration blockers before editing", "Plan a broad API/package migration with visible caps"],
	"complex-research": ["Research a migration or vendor choice with independent angles", "Collect and synthesize source-backed options", "Compare alternatives before implementation"],
	"plan-review": ["Review an implementation plan from security/performance/product angles", "Find reasons not to execute a proposed migration", "Get a skeptical panel before committing code"],
	"claim-bug-verification": ["Verify suspected bugs before reporting", "Check claims from a previous sweep", "Separate true findings from unsupported suspicions"],
};

// Keep pattern scaffolds self-contained in this extension so packaged installs do not
// depend on examples/workflows/ being present at runtime.
const EMBEDDED_WORKFLOW_PATTERN_TEMPLATES: Record<string, string> = {
	"scout-fanout": [
		"/**",
		" * Scout -> dynamic fan-out -> pipeline with per-item adaptive depth.",
		" *",
		" * The work-list is DISCOVERED by scouting inline (not assumed), then each file",
		" * flows through a pipeline: a cheap structured classification, and a deep review",
		" * ONLY for the items that turn out high-signal. Low-risk items short-circuit.",
		" * That per-item branching (spend more only where it pays) is dynamism.",
		" *",
		" * Uses: ctx.bash (scout), ctx.pipeline(items, ...stages) with stage",
		" * (value, originalItem, index), ctx.agent({ schema }) for a typed verdict.",
		" */",
		"module.exports = async function workflow(ctx, input) {",
		"  const safeParse = (s) => { try { return JSON.parse(s); } catch { return undefined; } };",
		"  const pattern = input?.pattern ?? \"\\\\.(ts|tsx|js|jsx|py|go|rs)$\";",
		"  const maxFiles = Number(input?.maxFiles ?? 40);",
		"",
		"  // 1) SCOUT inline \u2014 discover the real work-list and its size before committing.",
		"  // Filter in JS (not the shell) so input.pattern cannot inject shell commands.",
		"  const fileRe = new RegExp(pattern);",
		"  const scout = await ctx.bash(\"git ls-files\", { throwOnError: true });",
		"  const files = scout.stdout.split(\"\\n\").filter(Boolean).filter((f) => fileRe.test(f)).slice(0, maxFiles);",
		"  await ctx.log(`scouted ${files.length} files`, { pattern });",
		"  if (files.length === 0) return \"No files matched; nothing to review.\";",
		"",
		"  const VERDICT = {",
		"    type: \"object\",",
		"    additionalProperties: false,",
		"    required: [\"risk\", \"why\"],",
		"    properties: {",
		"      risk: { type: \"string\", description: \"one of: high | medium | low\" },",
		"      why: { type: \"string\", description: \"one short sentence\" },",
		"    },",
		"  };",
		"",
		"  // 2) PIPELINE: classify every file (cheap), deep-review only high/medium (adaptive depth).",
		"  const reviewed = await ctx.pipeline(",
		"    files,",
		"    (file, _orig, i) =>",
		"      ctx.agent(`Classify the risk of bugs/security issues in ${file}. Be quick; do not deep-dive.`, {",
		"        name: `classify-${i}`,",
		"        agentType: \"reviewer\",",
		"        tools: [\"read\", \"grep\"],",
		"        schema: VERDICT,",
		"      }).then((r) => ({ file, verdict: r.data ?? safeParse(r.output) })),",
		"    (c, _orig, i) => {",
		"      const risk = c.verdict?.risk;",
		"      if (risk !== \"high\" && risk !== \"medium\") return { ...c, deep: null }; // short-circuit low risk",
		"      return ctx.agent(",
		"        `Deep review ${c.file} for the risk you flagged (\"${c.verdict?.why}\"). Cite file:line for each finding; say NO_FINDINGS if none.`,",
		"        { name: `deep-${i}`, agentType: \"reviewer\", tools: [\"read\", \"grep\", \"find\", \"ls\"] },",
		"      ).then((r) => ({ ...c, deep: r.output }));",
		"    },",
		"  );",
		"",
		"  const findings = reviewed",
		"    .filter(Boolean)",
		"    .filter((c) => c.deep && !/NO_FINDINGS/.test(c.deep));",
		"  await ctx.writeArtifact(\"reviewed.json\", reviewed);",
		"  await ctx.log(`deep-reviewed ${findings.length}/${files.length} (rest were low-risk or clean)`);",
		"",
		"  const synthesis = await ctx.agent(",
		"    `Synthesize prioritized findings from these deep reviews. Deduplicate and drop unsupported claims.\\n\\n${ctx.compact(findings, 60000)}`,",
		"    { name: \"synthesis\", agentType: \"reviewer\", tools: [\"read\", \"grep\", \"find\", \"ls\"] },",
		"  );",
		"  return synthesis.output;",
		"};",
		"",
	].join("\n"),
	"loop-until-dry": [
		"/**",
		" * Dynamic discovery \u2014 loop-until-dry.",
		" *",
		" * Depth is NOT fixed up front: keep fanning out finders until K consecutive",
		" * rounds surface nothing new. This is the hallmark of a *dynamic* workflow \u2014",
		" * the shape adapts to what is found, instead of a static \"map N items -> synth\".",
		" *",
		" * Uses: ctx.agents({ settle:true }) (one crashed finder doesn't sink the round),",
		" * a dedupe Set keyed by a stable id, and ctx.log so the cap is never silent.",
		" */",
		"module.exports = async function workflow(ctx, input) {",
		"  const quietToStop = input?.quietRounds ?? 2;",
		"  const maxRounds = input?.maxRounds ?? 8;",
		"  const finders = input?.finders ?? 3;",
		"  const seen = new Set();",
		"  const all = [];",
		"  let quiet = 0;",
		"  let round = 0;",
		"",
		"  while (quiet < quietToStop && round < maxRounds) {",
		"    round++;",
		"    const concurrency = Math.min(finders, ctx.limits.concurrency);",
		"    const batches = await ctx.agents(",
		"      Array.from({ length: finders }, (_unused, i) => ({",
		"        name: `find-r${round}-a${i + 1}`,",
		"        prompt:",
		"          `Find NEW issues NOT already in the list below (dedupe by a short stable id). ` +",
		"          `Look from angle #${i + 1} (use a different search strategy than the other finders). ` +",
		"          `Return a JSON array of { id, title, evidence }; return [] if nothing new.\\n\\n` +",
		"          `Already found:\\n${ctx.compact([...seen], 4000)}`,",
		"        tools: [\"read\", \"grep\", \"find\", \"ls\"],",
		"        cache: false, // discovery must re-look each round, never serve a cached hit",
		"      })),",
		"      { concurrency, settle: true },",
		"    );",
		"",
		"    let fresh = 0;",
		"    for (const r of batches.filter(Boolean)) {",
		"      let arr = [];",
		"      try { arr = JSON.parse(r.output); } catch { /* tolerate non-JSON finders */ }",
		"      for (const item of Array.isArray(arr) ? arr : []) {",
		"        if (item && item.id && !seen.has(item.id)) {",
		"          seen.add(item.id);",
		"          all.push(item);",
		"          fresh++;",
		"        }",
		"      }",
		"    }",
		"    await ctx.log(`round ${round}: +${fresh} new (${all.length} total)`, { quiet });",
		"    quiet = fresh === 0 ? quiet + 1 : 0;",
		"  }",
		"",
		"  if (round >= maxRounds && quiet < quietToStop) {",
		"    // No silent caps: say we stopped on the round budget, not because we ran dry.",
		"    await ctx.log(\"stopped at maxRounds (not dry)\", { maxRounds, total: all.length });",
		"  }",
		"",
		"  await ctx.writeArtifact(\"findings.json\", all);",
		"  const synthesis = await ctx.agent(",
		"    `Synthesis-as-judge over every round. Deduplicate, drop unsupported claims, prioritize by severity, keep evidence.\\n\\n${ctx.compact(all, 60000)}`,",
		"    { name: \"synthesis\", agentType: \"reviewer\", tools: [\"read\", \"grep\", \"find\", \"ls\"] },",
		"  );",
		"  return synthesis.output;",
		"};",
		"",
	].join("\n"),
	"adversarial-verify": [
		"/**",
		" * Adversarial verify (vote) \u2014 per-finding skeptic fan-out that prunes by majority.",
		" *",
		" * Findings come from input.findings or are DISCOVERED by an inline finder. For",
		" * EACH finding we launch N independent skeptics whose only job is to REFUTE it",
		" * with evidence; if a skeptic is unsure it must default to refuted=true (guilty",
		" * until proven innocent). A finding survives only if FEWER than a majority of",
		" * skeptics refute it. The dynamism: the verification fan-out is sized and shaped",
		" * per finding (each gets its own jury), and survivors are decided by the votes \u2014",
		" * not by a fixed pass/fail oracle.",
		" *",
		" * Uses: ctx.agent (finder), ctx.parallel([thunks]) per finding (jury barrier),",
		" * ctx.agent({ schema }) for typed skeptic verdicts, result-driven survival.",
		" */",
		"module.exports = async function workflow(ctx, input) {",
		"  const safeParse = (s) => { try { return JSON.parse(s); } catch { return undefined; } };",
		"",
		"  // N skeptics per finding; clamp to the concurrency budget so one jury fits a barrier.",
		"  const skeptics = Math.max(1, Math.min(Number.isFinite(+input?.skeptics) ? Math.floor(+input.skeptics) : 3, ctx.limits.concurrency));",
		"",
		"  // 1) SOURCE the findings: take them as-is, or DISCOVER them with an inline finder.",
		"  let findings = Array.isArray(input?.findings) ? input.findings.filter(Boolean) : null;",
		"  if (!findings) {",
		"    const topic = input?.topic ?? input?.text;",
		"    if (!topic) throw new Error('Pass { findings: [...] } or { topic: \"...\" } as workflow input.');",
		"    const maxFind = Math.max(1, Number.isFinite(+input?.maxFindings) ? Math.floor(+input.maxFindings) : 8);",
		"    const finder = await ctx.agent(",
		"      `Find up to ${maxFind} concrete, checkable claims about: ${topic}.\\n` +",
		"        `Each must be falsifiable (a skeptic could try to refute it with evidence).\\n` +",
		"        `Return ONLY a JSON array of { id, claim, evidence }.`,",
		"      { name: \"finder\", agentType: \"researcher\", tools: [\"read\", \"grep\", \"find\", \"ls\", \"bash\"] },",
		"    );",
		"    const arr = finder.data ?? safeParse(finder.output);",
		"    findings = (Array.isArray(arr) ? arr : []).slice(0, maxFind);",
		"    await ctx.log(`finder produced ${findings.length} findings (cap ${maxFind})`, { topic });",
		"  }",
		"  if (findings.length === 0) return \"No findings to verify.\";",
		"",
		"  // Normalize to { id, claim, evidence } so prompts and reporting are stable.",
		"  const items = findings.map((f, i) => {",
		"    if (typeof f === \"string\") return { id: `f${i + 1}`, claim: f, evidence: \"\" };",
		"    return { id: f.id ?? `f${i + 1}`, claim: f.claim ?? f.title ?? ctx.json(f), evidence: f.evidence ?? \"\" };",
		"  });",
		"",
		"  const VOTE = {",
		"    type: \"object\",",
		"    additionalProperties: false,",
		"    required: [\"refuted\", \"why\"],",
		"    properties: {",
		"      // Default-refuted is the adversarial bias: doubt => kill it.",
		"      refuted: { type: \"boolean\", description: \"true if the claim is refuted OR you cannot confirm it; default true when unsure\" },",
		"      why: { type: \"string\", description: \"one sentence with the evidence for your vote\" },",
		"    },",
		"  };",
		"",
		"  const majority = Math.floor(skeptics / 2) + 1; // strict majority needed to kill a finding",
		"  await ctx.log(`verifying ${items.length} findings`, { skeptics, majority });",
		"",
		"  // 2) Per finding, run an independent jury of skeptics (barrier per finding).",
		"  const verified = [];",
		"  for (let fi = 0; fi < items.length; fi++) {",
		"    const item = items[fi];",
		"    const votes = await ctx.parallel(",
		"      Array.from({ length: skeptics }, (_unused, si) => () =>",
		"        ctx.agent(",
		"          `You are skeptic ${si + 1}/${skeptics} for finding ${item.id}. Your job is to REFUTE this claim with evidence; ` +",
		"            `do NOT try to confirm it. If you cannot find solid disproving evidence but also cannot independently confirm it, vote refuted=true (default to doubt).\\n\\n` +",
		"            `Claim: ${item.claim}\\n` +",
		"            `Cited evidence: ${item.evidence || \"(none)\"}\\n\\n` +",
		"            `Decide independently \u2014 assume the other skeptics may be wrong or may fail.`,",
		"          {",
		"            name: `skeptic-${item.id}-${si + 1}`,",
		"            agentType: \"reviewer\",",
		"            tools: [\"read\", \"grep\", \"find\", \"ls\", \"bash\"],",
		"            schema: VOTE,",
		"            // Independent juries must re-examine each finding, never serve a cached identical hit.",
		"            cache: false,",
		"          },",
		"        ).then((r) => r.data ?? safeParse(r.output)),",
		"      ),",
		"    );",
		"",
		"    // A null thunk (crashed skeptic) counts as a refute \u2014 fail closed, stay adversarial.",
		"    const cast = votes.map((v) => (v && typeof v.refuted === \"boolean\" ? v : { refuted: true, why: \"skeptic failed/invalid -> default refuted\" }));",
		"    const refutes = cast.filter((v) => v.refuted).length;",
		"    const survived = refutes < majority;",
		"    await ctx.log(`finding ${item.id}: ${refutes}/${skeptics} refuted -> ${survived ? \"SURVIVED\" : \"KILLED\"}`);",
		"    verified.push({ ...item, refutes, skeptics, survived, votes: cast });",
		"  }",
		"",
		"  const survivors = verified.filter((v) => v.survived);",
		"  const killed = verified.length - survivors.length;",
		"  await ctx.log(`verification complete: ${survivors.length} survived, ${killed} killed`, { total: verified.length });",
		"  await ctx.writeArtifact(\"verification.json\", verified);",
		"",
		"  return {",
		"    survivors: survivors.map(({ votes, ...keep }) => keep),",
		"    killedCount: killed,",
		"    totalFindings: verified.length,",
		"    skepticsPerFinding: skeptics,",
		"    majorityToKill: majority,",
		"  };",
		"};",
		"",
	].join("\n"),
	"judge-escalate": [
		"/**",
		" * Generate -> judge -> ADAPTIVE escalate (best-of-N that deepens only when unsure).",
		" *",
		" * Generates candidates from distinct angles and judges them with a typed verdict.",
		" * The dynamism: if the judge is NOT confident, spend more \u2014 another, more rigorous",
		" * round of candidates \u2014 instead of committing to a weak winner. Confident => stop.",
		" *",
		" * Uses: ctx.parallel([thunks]) (barrier: judge all together),",
		" * ctx.agent({ schema }) for a structured verdict, a result-driven while loop.",
		" */",
		"module.exports = async function workflow(ctx, input) {",
		"  const safeParse = (s) => { try { return JSON.parse(s); } catch { return undefined; } };",
		"  const question = input?.question ?? input?.q ?? input?.text;",
		"  if (!question) throw new Error('Pass { question: \"...\" } as workflow input.');",
		"  const angles = input?.angles ?? [\"risk-first\", \"simplicity-first\", \"user-first\"];",
		"  const maxEscalations = Number.isFinite(+input?.maxEscalations) ? Math.floor(+input.maxEscalations) : 2;",
		"",
		"  const VERDICT = {",
		"    type: \"object\",",
		"    additionalProperties: false,",
		"    required: [\"winner\", \"confidence\", \"why\"],",
		"    properties: {",
		"      winner: { type: \"number\", description: \"1-based index of the best candidate\" },",
		"      confidence: { type: \"string\", description: \"one of: high | medium | low\" },",
		"      why: { type: \"string\" },",
		"    },",
		"  };",
		"",
		"  const candidates = [];",
		"  let escalation = 0;",
		"  let verdict;",
		"",
		"  while (true) {",
		"    const tougher = escalation > 0",
		"      ? \" Be more rigorous than a basic answer; pre-empt the weaknesses a skeptical critic would raise.\"",
		"      : \"\";",
		"    const batch = await ctx.parallel(",
		"      angles.map((angle, i) => () =>",
		"        ctx.agent(`Propose an approach to the question below.\\nAngle: ${angle}.${tougher}\\n\\nQuestion: ${question}`, {",
		"          name: `cand-e${escalation}-${i}`,",
		"          agentType: \"researcher\",",
		"          tools: [\"read\", \"grep\", \"find\", \"ls\", \"bash\"],",
		"        }),",
		"      ),",
		"    );",
		"    batch.filter(Boolean).forEach((r, i) => candidates.push({ angle: angles[i], text: r.output }));",
		"",
		"    const j = await ctx.agent(",
		"      `You are the judge. Pick the single best candidate for the question. Be skeptical and demand evidence.\\n\\n` +",
		"        `Question: ${question}\\n\\n` +",
		"        candidates.map((c, i) => `### Candidate ${i + 1} (${c.angle})\\n${c.text}`).join(\"\\n\\n\"),",
		"      { name: `judge-e${escalation}`, agentType: \"reviewer\", tools: [\"read\", \"grep\", \"find\", \"ls\"], schema: VERDICT },",
		"    );",
		"    verdict = j.data ?? safeParse(j.output);",
		"    await ctx.log(`escalation ${escalation}: winner=${verdict?.winner} confidence=${verdict?.confidence}`);",
		"",
		"    // ADAPTIVE: stop when confident or out of budget; otherwise escalate with more candidates.",
		"    if (verdict?.confidence === \"high\" || escalation >= maxEscalations) break;",
		"    escalation++;",
		"  }",
		"",
		"  await ctx.writeArtifact(\"candidates.json\", { candidates, verdict });",
		"  const winner = candidates[(verdict?.winner ?? 1) - 1] ?? candidates[0];",
		"  const synthesis = await ctx.agent(",
		"    `Write the final answer to: ${question}\\n\\nBuild on the winning approach, grafting the best ideas from the runners-up; flag residual risks.\\n\\n` +",
		"      `WINNER (${winner?.angle}):\\n${winner?.text}\\n\\nALL CANDIDATES:\\n${ctx.compact(candidates, 40000)}`,",
		"    { name: \"synthesis\", agentType: \"researcher\", tools: [\"read\", \"grep\", \"find\", \"ls\", \"bash\"] },",
		"  );",
		"  return synthesis.output;",
		"};",
		"",
	].join("\n"),
	"tournament": [
		"/**",
		" * TOURNAMENT / single-elimination bracket \u2014 pairwise judging until one survives.",
		" *",
		" * Candidates come from input.candidates, or are generated from distinct angles.",
		" * Each round pairs survivors and a judge picks the better of every pair",
		" * (typed verdict { winner:1|2, why }); winners advance, repeat until one remains.",
		" *",
		" * The dynamism: NOTHING about the shape is fixed up front. The number of rounds",
		" * is ceil(log2(n)) and emerges from the data \u2014 the bracket halves every round and",
		" * the loop ends when the field collapses to a single survivor. An odd field gives",
		" * one candidate a free \"bye\" into the next round (no fabricated opponent).",
		" *",
		" * Uses: ctx.agents({ settle:true }) so a crashed match never sinks the whole round,",
		" * ctx.agent({ schema }) for structured pairwise verdicts, ctx.log so the bracket",
		" * size / byes / round count are never a silent cap.",
		" */",
		"module.exports = async function workflow(ctx, input) {",
		"  const safeParse = (s) => { try { return JSON.parse(s); } catch { return undefined; } };",
		"  const topic = input?.topic ?? input?.question ?? input?.q ?? input?.text;",
		"",
		"  // Seed the bracket: explicit candidates win; otherwise generate one per angle.",
		"  let entrants = Array.isArray(input?.candidates) ? input.candidates.filter(Boolean) : null;",
		"  if (!entrants || entrants.length === 0) {",
		"    if (!topic) throw new Error('Pass { candidates:[...] } or { topic:\"...\" } as workflow input.');",
		"    const angles = input?.angles ?? [\"risk-first\", \"simplicity-first\", \"user-first\", \"cost-first\"];",
		"    const gen = await ctx.agents(",
		"      angles.map((angle, i) => ({",
		"        name: `seed-${i}`,",
		"        prompt: `Propose ONE concrete approach to the topic below.\\nAngle: ${angle}.\\n\\nTopic: ${topic}`,",
		"        agentType: \"researcher\",",
		"        tools: [\"read\", \"grep\", \"find\", \"ls\", \"bash\"],",
		"      })),",
		"      { concurrency: Math.min(angles.length, ctx.limits.concurrency), settle: true },",
		"    );",
		"    // Map BEFORE filtering so each entrant keeps the angle label at its original",
		"    // index \u2014 a crashed seed (null) must not shift the labels of later entrants.",
		"    entrants = gen",
		"      .map((r, i) => (r ? `[${angles[i] ?? `angle-${i}`}] ${r.output}` : null))",
		"      .filter(Boolean);",
		"  }",
		"  if (entrants.length < 2) {",
		"    await ctx.log(\"only one entrant \u2014 no tournament needed\", { entrants: entrants.length });",
		"    return entrants[0] ?? \"\";",
		"  }",
		"",
		"  const VERDICT = {",
		"    type: \"object\",",
		"    additionalProperties: false,",
		"    required: [\"winner\", \"why\"],",
		"    properties: {",
		"      winner: { type: \"number\", description: \"1 if the first candidate is better, 2 if the second\" },",
		"      why: { type: \"string\" },",
		"    },",
		"  };",
		"",
		"  const totalRounds = Math.ceil(Math.log2(entrants.length));",
		"  await ctx.log(`tournament start: ${entrants.length} entrants -> ~${totalRounds} rounds`);",
		"",
		"  // BRACKET: each iteration halves the field; loop ends when one survivor remains.",
		"  let survivors = entrants.map((text, i) => ({ id: `e${i}`, text }));",
		"  let round = 0;",
		"  const transcript = [];",
		"",
		"  while (survivors.length > 1) {",
		"    round++;",
		"    // Pair up survivors; an odd field gives the last one a bye (advances for free).",
		"    const pairs = [];",
		"    let bye = null;",
		"    for (let i = 0; i < survivors.length; i += 2) {",
		"      if (i + 1 < survivors.length) pairs.push([survivors[i], survivors[i + 1]]);",
		"      else bye = survivors[i];",
		"    }",
		"    await ctx.log(`round ${round}/${totalRounds}: ${survivors.length} in, ${pairs.length} matches${bye ? \" + 1 bye\" : \"\"}`, {",
		"      byeId: bye?.id ?? null,",
		"    });",
		"",
		"    const matches = await ctx.agents(",
		"      pairs.map(([a, b], i) => ({",
		"        // Stable id (round + match) keeps the per-prompt cache from colliding across rounds.",
		"        name: `match-r${round}-m${i}`,",
		"        prompt:",
		"          `You are the judge of a single match. Pick the BETTER candidate for the goal` +",
		"          (topic ? ` (topic: ${topic})` : \"\") +",
		"          `. Be skeptical and demand substance over polish.\\n\\n` +",
		"          `### Candidate 1\\n${a.text}\\n\\n### Candidate 2\\n${b.text}`,",
		"        agentType: \"reviewer\",",
		"        tools: [\"read\", \"grep\", \"find\", \"ls\"],",
		"        schema: VERDICT,",
		"      })),",
		"      { concurrency: Math.min(Math.max(pairs.length, 1), ctx.limits.concurrency), settle: true },",
		"    );",
		"",
		"    const next = [];",
		"    matches.forEach((r, i) => {",
		"      const [a, b] = pairs[i];",
		"      const v = r ? (r.data ?? safeParse(r.output)) : undefined;",
		"      // Tolerate a crashed/invalid match: default to candidate 1 rather than dropping both.",
		"      const winner = v?.winner === 2 ? b : a;",
		"      transcript.push({ round, match: i, a: a.id, b: b.id, winner: winner.id, why: v?.why ?? \"(default: judge unavailable)\" });",
		"      next.push(winner);",
		"    });",
		"    if (bye) next.push(bye);",
		"    survivors = next;",
		"  }",
		"",
		"  const champion = survivors[0];",
		"  await ctx.log(`champion after ${round} rounds: ${champion?.id}`);",
		"  await ctx.writeArtifact(\"tournament.json\", { entrants: entrants.length, rounds: round, transcript, championId: champion?.id });",
		"",
		"  return champion?.text ?? \"\";",
		"};",
		"",
	].join("\n"),
	"workflow-factory": [
		"/**",
		" * Workflow factory / meta-workflow.",
		" *",
		" * Given a task, spend one workflow run designing the RIGHT task-specific",
		" * workflow: improve prompts, choose primitives/patterns, generate code, review",
		" * it, then write the gitignored `.pi/workflows/drafts/<slug>.js` draft by default.",
		" *",
		" * Input: { task: \"...\", name?: \"<slug>\", write?: boolean }",
		" * - write=false keeps the generated JS as artifacts only.",
		" * - The generated workflow is a draft: inspect/edit before trusting it for high",
		" *   cost or mutating work.",
		" */",
		"module.exports = async function workflow(ctx, input) {",
		"  const task = input?.task ?? input?.request ?? input?.text;",
		"  if (!task) throw new Error('Pass { task: \"what the workflow should accomplish\" }.');",
		"",
		"  const slug = (value) => String(value)",
		"    .toLowerCase()",
		"    .replace(/[^a-z0-9._/-]+/g, \"-\")",
		"    .replace(/(^|\\/)\\.\\.(?=\\/|$)/g, \"\")",
		"    .replace(/^-+|-+$/g, \"\")",
		"    .slice(0, 80) || \"workflow-draft\";",
		"  const safeName = slug(input?.name ?? slug(task));",
		"  const workflowName = safeName.endsWith(\".js\") ? safeName.slice(0, -3) : safeName;",
		"  const workflowPath = `.pi/workflows/drafts/${workflowName}.js`;",
		"  const extractJs = (text) => {",
		"    const match = /```(?:js|javascript)?\\s*\\n([\\s\\S]*?)```/i.exec(String(text ?? \"\"));",
		"    return (match ? match[1] : String(text ?? \"\")).trim();",
		"  };",
		"",
		"  const PLAN = {",
		"    type: \"object\",",
		"    additionalProperties: false,",
		"    required: [\"name\", \"pattern\", \"why\", \"inputs\", \"scout\", \"primitives\", \"promptContracts\", \"verification\", \"risks\"],",
		"    properties: {",
		"      name: { type: \"string\" },",
		"      pattern: { type: \"string\" },",
		"      why: { type: \"string\" },",
		"      inputs: { type: \"array\", items: { type: \"string\" } },",
		"      scout: { type: \"string\" },",
		"      primitives: { type: \"array\", items: { type: \"string\" } },",
		"      promptContracts: { type: \"array\", items: { type: \"string\" } },",
		"      verification: { type: \"array\", items: { type: \"string\" } },",
		"      risks: { type: \"array\", items: { type: \"string\" } },",
		"    },",
		"  };",
		"",
		"  await ctx.log(\"workflow-factory planning\", { task, workflowName });",
		"  const planResult = await ctx.agent(",
		"    `Design a Pi dynamic workflow for this task. Choose the minimal sufficient orchestration pattern.\\n\\n` +",
		"      `Task:\\n${task}\\n\\n` +",
		"      `Available primitives: ctx.agent, ctx.agents({settle}), ctx.pipeline, ctx.parallel, ctx.workflow for reusable sub-steps, ctx.bash, ctx.writeArtifact.\\n` +",
		"      `Default subagent access: web_search is added when pi-codex-web-search is installed, and context7-cli is available when installed; do not opt out unless isolation is required.\\n` +",
		"      `Return JSON matching the schema. Include prompt contracts with evidence rules, partial-failure handling, caps, and verification strategy.`,",
		"    { name: \"workflow-plan\", agentType: \"planner\", tools: [\"read\", \"grep\", \"find\", \"ls\"], schema: PLAN },",
		"  );",
		"  const plan = planResult.data ?? { name: workflowName, pattern: \"custom\", why: \"planner returned unstructured output\" };",
		"  await ctx.writeArtifact(\"workflow-plan.json\", plan);",
		"",
		"  const implement = await ctx.agent(",
		"    `Generate a COMPLETE JavaScript Pi dynamic workflow for this task. Return ONLY JavaScript, no Markdown fences.\\n\\n` +",
		"      `Task:\\n${task}\\n\\n` +",
		"      `Design plan:\\n${ctx.compact(plan, 12000)}\\n\\n` +",
		"      `Hard requirements:\\n` +",
		"      `- module.exports = async function workflow(ctx, input) { ... }\\n` +",
		"      `- No import/require. Use only ctx helpers and plain JS.\\n` +",
		"      `- Choose concurrency from input/ctx.limits; never silently cap coverage.\\n` +",
		"      `- Use read-only subagent tools unless the task explicitly requires mutation; include web_search when web/docs/current evidence may help.\\n` +",
		"      `- Dynamic Workflows auto-loads web_search and context7-cli when installed; do not set includeExtensions:false/includeSkills:false unless explicitly opting out.\\n` +",
		"      `- Persist artifacts for work-list, raw branch outputs, review notes, and final summary.\\n` +",
		"      `- Use evidence contracts: cite files/lines/URLs/commands or say NO_FINDINGS/INSUFFICIENT_EVIDENCE.\\n` +",
		"      `- If a reusable sub-step is needed with no human decision in between, call ctx.workflow(name, args); otherwise keep phases in this workflow.`,",
		"    { name: \"workflow-codegen\", agentType: \"implementer\", tools: [\"read\", \"grep\", \"find\", \"ls\"] },",
		"  );",
		"  let code = extractJs(implement.output);",
		"  await ctx.writeArtifact(\"generated-workflow.initial.js\", code);",
		"",
		"  const review = await ctx.agent(",
		"    `Review this generated Pi workflow for correctness, cost, safety, prompt quality, and composability.\\n` +",
		"      `Find concrete issues only; cite the problematic snippet. If it is acceptable, say APPROVED.\\n\\n` +",
		"      `Task:\\n${task}\\n\\nWorkflow code:\\n\\n${code}`,",
		"    { name: \"workflow-review\", agentType: \"reviewer\", tools: [\"read\", \"grep\", \"find\", \"ls\"] },",
		"  );",
		"  await ctx.writeArtifact(\"workflow-review.md\", review.output);",
		"",
		"  const refine = await ctx.agent(",
		"    `Revise the workflow code to address this review. Return ONLY final JavaScript.\\n\\n` +",
		"      `Task:\\n${task}\\n\\nReview:\\n${review.output}\\n\\nCurrent code:\\n\\n${code}`,",
		"    { name: \"workflow-refine\", agentType: \"implementer\", tools: [\"read\", \"grep\", \"find\", \"ls\"] },",
		"  );",
		"  code = extractJs(refine.output);",
		"  await ctx.writeArtifact(\"generated-workflow.js\", code);",
		"",
		"  let written;",
		"  if (input?.write !== false) {",
		"    written = await ctx.writeFile(workflowPath, `${code}\\n`);",
		"    await ctx.log(\"generated workflow written\", { path: written.path, workflowName });",
		"  } else {",
		"    await ctx.log(\"write=false: generated workflow kept as artifacts only\", { workflowName });",
		"  }",
		"",
		"  return [",
		"    `Generated workflow draft: ${workflowName}`,",
		"    written ? `Wrote: ${written.path}` : \"Not written (write=false); see artifact generated-workflow.js.\",",
		"    `Pattern: ${plan.pattern ?? \"custom\"}`,",
		"    `Why: ${plan.why ?? \"n/a\"}`,",
		"    \"Next: inspect/edit the generated workflow, then run it with explicit concurrency/maxAgents.\",",
		"  ].join(\"\\n\");",
		"};",
		"",
	].join("\n"),
	"composition-driver": [
		"/**",
		" * Composition driver \u2014 parent workflow calling a reusable sub-workflow.",
		" *",
		" * Requires a sibling project/global workflow at `lib/verify-claims` (use the",
		" * `verify-claims-lib` pattern). The parent discovers claims, then delegates the",
		" * reusable verification phase with ctx.workflow(\"lib/verify-claims\", args).",
		" *",
		" * Input: { topic: \"...\", maxClaims?: 8, skeptics?: 3 }",
		" */",
		"module.exports = async function workflow(ctx, input) {",
		"  const topic = input?.topic ?? input?.question ?? input?.text;",
		"  if (!topic) throw new Error('Pass { topic: \"claims to discover and verify\" }.');",
		"  const maxClaims = Math.max(1, Number.isFinite(+input?.maxClaims) ? Math.floor(+input.maxClaims) : 8);",
		"",
		"  const finder = await ctx.agent(",
		"    `Find up to ${maxClaims} concrete, falsifiable claims about the topic below. ` +",
		"      `Return ONLY a JSON array of { id, claim, evidence }. Evidence can be a file:line, URL, or command observation.\\n\\n` +",
		"      `Topic: ${topic}`,",
		"    { name: \"claim-finder\", agentType: \"researcher\", tools: [\"read\", \"grep\", \"find\", \"ls\", \"bash\"] },",
		"  );",
		"",
		"  let claims = [];",
		"  try { claims = JSON.parse(finder.output); } catch { claims = []; }",
		"  claims = Array.isArray(claims) ? claims.filter((claim) => claim && claim.claim).slice(0, maxClaims) : [];",
		"  if (claims.length === 0) return \"No falsifiable claims found to verify.\";",
		"  if (claims.length >= maxClaims) await ctx.log(\"claim cap applied\", { reviewed: claims.length, maxClaims });",
		"  await ctx.writeArtifact(\"claims.json\", claims);",
		"",
		"  const verification = await ctx.workflow(\"lib/verify-claims\", {",
		"    claims,",
		"    skeptics: input?.skeptics ?? 3,",
		"    topic,",
		"  });",
		"  await ctx.writeArtifact(\"verification.json\", verification);",
		"",
		"  const synthesis = await ctx.agent(",
		"    `Synthesize the verified/dropped claims below. Preserve uncertainty, cite evidence, and mention that verification was delegated to lib/verify-claims.\\n\\n` +",
		"      `${ctx.compact(verification, 50000)}`,",
		"    { name: \"composition-synthesis\", agentType: \"reviewer\", tools: [\"read\", \"grep\", \"find\", \"ls\"] },",
		"  );",
		"  await ctx.writeArtifact(\"summary.md\", synthesis.output);",
		"  return synthesis.output;",
		"};",
		"",
	].join("\n"),
	"verify-claims-lib": [
		"/**",
		" * lib/verify-claims \u2014 reusable composable sub-workflow.",
		" *",
		" * Contract: { claims:[{id, claim, evidence?}], skeptics?: number, topic?: string }",
		" * Returns: { verified, dropped, votes, coverage }",
		" *",
		" * This file is intended to live at `.pi/workflows/lib/verify-claims.js` and be",
		" * called from parent workflows with ctx.workflow(\"lib/verify-claims\", args).",
		" */",
		"module.exports = async function workflow(ctx, input) {",
		"  const claims = Array.isArray(input?.claims) ? input.claims.filter((claim) => claim && claim.claim) : [];",
		"  if (claims.length === 0) return { verified: [], dropped: [], votes: [], coverage: { claims: 0 } };",
		"  const requestedSkeptics = Math.max(1, Number(input?.skeptics ?? 3));",
		"  const skeptics = Math.min(requestedSkeptics, ctx.limits.concurrency);",
		"  if (skeptics < requestedSkeptics) await ctx.log(\"skeptic cap applied\", { requested: requestedSkeptics, running: skeptics, concurrency: ctx.limits.concurrency });",
		"",
		"  const VERDICT = {",
		"    type: \"object\",",
		"    additionalProperties: false,",
		"    required: [\"refuted\", \"confidence\", \"evidence\", \"why\"],",
		"    properties: {",
		"      refuted: { type: \"boolean\" },",
		"      confidence: { type: \"string\", description: \"high | medium | low\" },",
		"      evidence: { type: \"string\" },",
		"      why: { type: \"string\" },",
		"    },",
		"  };",
		"",
		"  const votes = [];",
		"  const verified = [];",
		"  const dropped = [];",
		"",
		"  for (let i = 0; i < claims.length; i++) {",
		"    const claim = claims[i];",
		"    const jury = await ctx.agents(",
		"      Array.from({ length: skeptics }, (_unused, j) => ({",
		"        name: `verify-${claim.id ?? i}-skeptic-${j + 1}`,",
		"        prompt:",
		"          `You are skeptic ${j + 1}/${skeptics}. Try to REFUTE this claim with concrete evidence. ` +",
		"          `If evidence is insufficient, set refuted=true unless the claim is strongly supported.\\n\\n` +",
		"          `Topic: ${input?.topic ?? \"n/a\"}\\n` +",
		"          `Claim: ${claim.claim}\\n` +",
		"          `Provided evidence: ${claim.evidence ?? \"none\"}\\n\\n` +",
		"          `Return JSON only matching the schema.`,",
		"        agentType: \"reviewer\",",
		"        tools: [\"read\", \"grep\", \"find\", \"ls\", \"bash\"],",
		"        schema: VERDICT,",
		"        schemaOnInvalid: \"null\",",
		"      })),",
		"      { concurrency: skeptics, settle: true },",
		"    );",
		"    const parsed = jury.filter(Boolean).map((result) => result.data).filter(Boolean);",
		"    const refutations = parsed.filter((vote) => vote.refuted).length;",
		"    const survived = parsed.length > 0 && refutations < Math.ceil(parsed.length / 2);",
		"    const record = { claim, parsedVotes: parsed, failedBranches: jury.length - parsed.length, refutations, survived };",
		"    votes.push(record);",
		"    if (survived) verified.push({ ...claim, verification: record });",
		"    else dropped.push({ ...claim, verification: record });",
		"    await ctx.log(\"claim verification complete\", { index: i + 1, total: claims.length, survived, refutations, votes: parsed.length, failedBranches: record.failedBranches });",
		"  }",
		"",
		"  const result = { verified, dropped, votes, coverage: { claims: claims.length, skeptics, requestedSkeptics } };",
		"  await ctx.writeArtifact(\"verify-claims-result.json\", result);",
		"  return result;",
		"};",
		"",
	].join("\n"),
	"complex-research": [
		"function chooseConcurrency(ctx, input, items, opts = {}) {",
		"  if (Number.isFinite(input?.concurrency)) {",
		"    return Math.min(Math.max(Math.floor(input.concurrency), 1), ctx.limits.concurrency, Math.max(1, items.length));",
		"  }",
		"  if (items.length <= 1) return 1;",
		"  if (opts.usesWeb) return Math.min(3, items.length, ctx.limits.concurrency);",
		"  if (items.length >= 8) return Math.min(6, items.length, ctx.limits.concurrency);",
		"  return Math.min(4, items.length, ctx.limits.concurrency); // small/safe fallback, not a default ceiling",
		"}",
		"",
		"module.exports = async function workflow(ctx, input) {",
		"  const question = input?.question ?? input?.q ?? input?.text;",
		"  if (!question) throw new Error(\"Pass { question: \\\"...\\\" } as workflow input.\");",
		"",
		"  const angles = input?.angles ?? [",
		"    \"official documentation and primary sources\",",
		"    \"implementation options and tradeoffs\",",
		"    \"risks, gotchas, and migration concerns\",",
		"    \"best current recommendation with evidence\",",
		"  ];",
		"  const concurrency = chooseConcurrency(ctx, input, angles, { usesWeb: true });",
		"",
		"  await ctx.log(\"Starting deep research\", { question, angles, concurrency });",
		"",
		"  const research = await ctx.agents(",
		"    angles.map((angle, index) => ({",
		"      name: `research-${String(angle).slice(0, 40)}`,",
		"      prompt: `Research this question from the perspective of: ${angle}.",
		"",
		"Question: ${question}",
		"",
		"Pattern: independent research fan-out. This is branch ${index + 1}/${angles.length}. Your answer must be useful even if other agents fail.",
		"",
		"Evidence rules:",
		"- Prefer official docs, primary sources, repository evidence, and concrete observed behavior.",
		"- Cite URLs, files/lines, or commands only if actually used/observed.",
		"- Separate facts, interpretation, and open questions.",
		"- If evidence is insufficient, say INSUFFICIENT_EVIDENCE and explain what would be needed.",
		"",
		"Output format:",
		"## Key findings",
		"## Evidence / sources",
		"## Tradeoffs",
		"## Risks / gotchas",
		"## Recommendation for this angle`,",
		"      tools: [\"read\", \"grep\", \"find\", \"ls\", \"web_search\"],",
		"      includeExtensions: true,",
		"      agentType: \"researcher\",",
		"      timeoutMs: input?.agentTimeoutMs ?? ctx.limits.agentTimeoutMs,",
		"    })),",
		"    { concurrency, settle: true },",
		"  );",
		"",
		"  const completedResearch = research.filter(Boolean);",
		"  const failed = research.length - completedResearch.length;",
		"  await ctx.log(\"research fan-out complete\", { total: research.length, completed: completedResearch.length, failed });",
		"  await ctx.writeArtifact(\"research.json\", research);",
		"",
		"  const synthesis = await ctx.agent(",
		"    `Synthesize this research into a final answer.",
		"",
		"Pattern: synthesis-as-judge. Deduplicate, prefer primary evidence, mark uncertainty, and mention failed/empty research outputs.",
		"",
		"Question: ${question}",
		"",
		"Coverage:",
		"- Angles requested: ${angles.length}",
		"- Completed branches: ${completedResearch.length}",
		"- Failed/empty branches: ${failed}",
		"",
		"Output format:",
		"1. Executive summary.",
		"2. Recommendation.",
		"3. Evidence/sources.",
		"4. Tradeoffs and alternatives.",
		"5. Risks/open questions.",
		"6. Coverage gaps and what to verify next.",
		"",
		"Research outputs:",
		"${ctx.compact(completedResearch, 90000)}`,",
		"    { name: \"research-synthesis\", tools: [\"read\", \"grep\", \"find\", \"ls\", \"web_search\"], includeExtensions: true, agentType: \"researcher\", timeoutMs: input?.agentTimeoutMs ?? ctx.limits.agentTimeoutMs },",
		"  );",
		"",
		"  await ctx.writeArtifact(\"synthesis.md\", synthesis.output);",
		"  return synthesis.output;",
		"};",
		"",
	].join("\n"),
	"repo-bug-hunt": [
		"function chooseConcurrency(ctx, input, items, opts = {}) {",
		"  if (Number.isFinite(input?.concurrency)) {",
		"    return Math.min(Math.max(Math.floor(input.concurrency), 1), ctx.limits.concurrency, Math.max(1, items.length));",
		"  }",
		"  if (items.length <= 1) return 1;",
		"  if (opts.expensiveModel || opts.sharedState) return Math.min(2, items.length, ctx.limits.concurrency);",
		"  if (opts.readOnlyAudit && items.length >= 50) return Math.min(12, items.length, ctx.limits.concurrency);",
		"  if (opts.readOnlyAudit && items.length >= 20) return Math.min(8, items.length, ctx.limits.concurrency);",
		"  if (items.length >= 8 && !opts.expensiveModel) return Math.min(6, items.length, ctx.limits.concurrency);",
		"  return Math.min(4, items.length, ctx.limits.concurrency); // small/safe fallback, not a default ceiling",
		"}",
		"",
		"module.exports = async function workflow(ctx, input) {",
		"  const maxFiles = input?.maxFiles ?? 40;",
		"",
		"  await ctx.log(\"Collecting candidate files\", { maxFiles });",
		"  const filesResult = await ctx.bash(",
		"    \"git ls-files | grep -E '\\\\.(ts|tsx|js|jsx|py|go|rs)$'\",",
		"    { throwOnError: true },",
		"  );",
		"  const allFiles = filesResult.stdout.split(\"\\n\").filter(Boolean);",
		"  const files = allFiles.slice(0, Number(maxFiles));",
		"  if (files.length < allFiles.length) {",
		"    await ctx.log(\"candidate file cap applied\", { reviewed: files.length, total: allFiles.length, skipped: allFiles.length - files.length });",
		"  }",
		"  await ctx.writeArtifact(\"candidate-files.json\", files);",
		"",
		"  const concurrency = chooseConcurrency(ctx, input, files, { readOnlyAudit: true });",
		"  await ctx.log(\"bug-hunt fan-out selected\", { files: files.length, concurrency, maxAgents: ctx.limits.maxAgents });",
		"",
		"  const reviews = await ctx.agents(",
		"    files.map((file, index) => ({",
		"      name: `bug-hunt-${file}`,",
		"      prompt: `Inspect ${file} for likely bugs, race conditions, security issues, data-loss risks, or edge-case failures.",
		"",
		"Pattern: independent file-level bug hunt. This is branch ${index + 1}/${files.length}. Your report must be useful even if other branches fail. Be skeptical but evidence-based. Do not edit files.",
		"",
		"Evidence rules:",
		"- Cite file and line numbers for every finding.",
		"- Explain the failing scenario, impact, and minimal fix.",
		"- Ignore pure style unless it can cause a real failure.",
		"- If there are no credible findings, say NO_FINDINGS.",
		"- If evidence is insufficient, say INSUFFICIENT_EVIDENCE and explain what would be needed.",
		"",
		"Output format:",
		"## Verdict",
		"## Findings",
		"- Severity High/Medium/Low | Confidence High/Medium/Low | Evidence | Scenario | Fix",
		"## Non-findings / notes`,",
		"      tools: [\"read\", \"grep\", \"find\", \"ls\"],",
		"      agentType: \"reviewer\",",
		"      timeoutMs: input?.agentTimeoutMs ?? ctx.limits.agentTimeoutMs,",
		"    })),",
		"    { concurrency, settle: true },",
		"  );",
		"",
		"  const completedReviews = reviews.filter(Boolean);",
		"  const failed = reviews.length - completedReviews.length;",
		"  await ctx.log(\"bug-hunt fan-out complete\", { total: reviews.length, completed: completedReviews.length, failed });",
		"  await ctx.writeArtifact(\"reviews.json\", reviews);",
		"",
		"  const synthesis = await ctx.agent(",
		"    `You are the final reviewer.",
		"",
		"Pattern: synthesis-as-judge. Deduplicate and prioritize findings. Only include credible, actionable issues with evidence. Discard uncited concrete claims. Mention partial failures and coverage caps explicitly.",
		"",
		"Coverage:",
		"- Reviewed files: ${files.length}/${allFiles.length}",
		"- Failed/empty branches: ${failed}",
		"",
		"Output format:",
		"1. Executive verdict.",
		"2. Prioritized findings table: severity | confidence | file/line | issue | scenario | fix.",
		"3. Findings rejected as low-confidence or unsupported.",
		"4. Coverage gaps / failed branches.",
		"5. Suggested verification/tests.",
		"",
		"Reviews:",
		"${ctx.compact(completedReviews, 80000)}`,",
		"    { name: \"synthesis\", tools: [\"read\", \"grep\", \"find\", \"ls\"], agentType: \"reviewer\", timeoutMs: input?.agentTimeoutMs ?? ctx.limits.agentTimeoutMs },",
		"  );",
		"",
		"  await ctx.writeArtifact(\"summary.md\", synthesis.output);",
		"  return synthesis.output;",
		"};",
		"",
	].join("\n"),
	"adversarial-plan-review": [
		"function chooseConcurrency(ctx, input, items) {",
		"  if (Number.isFinite(input?.concurrency)) {",
		"    return Math.min(Math.max(Math.floor(input.concurrency), 1), ctx.limits.concurrency, Math.max(1, items.length));",
		"  }",
		"  return Math.min(4, items.length, ctx.limits.concurrency); // small/safe fallback for bounded reviewer panels",
		"}",
		"",
		"module.exports = async function workflow(ctx, input) {",
		"  const plan = input?.plan ?? input?.text;",
		"  if (!plan) throw new Error(\"Pass { plan: \\\"...\\\" } as workflow input.\");",
		"",
		"  const sharedContract = `",
		"Pattern: independent adversarial review. Do not edit files. Do not assume other reviewers will cover missing issues.",
		"Evidence rules:",
		"- Cite files/lines when the plan references repository code.",
		"- Separate confirmed issues from speculative risks.",
		"- Prefer actionable, high-signal feedback over generic warnings.",
		"- If evidence is insufficient, say INSUFFICIENT_EVIDENCE.",
		"Output format:",
		"## Verdict",
		"## Must-fix issues",
		"## Should-fix issues",
		"## Questions / missing evidence",
		"## Smallest safe path`;",
		"",
		"  const reviewers = [",
		"    {",
		"      name: \"correctness-reviewer\",",
		"      angle: \"correctness risks, missing edge cases, and invalid assumptions\",",
		"    },",
		"    {",
		"      name: \"security-reviewer\",",
		"      angle: \"security, privacy, permission, and data-loss risks\",",
		"    },",
		"    {",
		"      name: \"maintainability-reviewer\",",
		"      angle: \"maintainability, complexity, testability, and future migration concerns\",",
		"    },",
		"    {",
		"      name: \"scope-reviewer\",",
		"      angle: \"scope creep; what to remove, defer, or simplify while preserving the goal\",",
		"    },",
		"  ];",
		"",
		"  const concurrency = chooseConcurrency(ctx, input, reviewers);",
		"  await ctx.log(\"adversarial review fan-out selected\", { reviewers: reviewers.length, concurrency });",
		"",
		"  const critiques = await ctx.agents(reviewers.map((reviewer, index) => ({",
		"    name: reviewer.name,",
		"    prompt: `Review this implementation plan for ${reviewer.angle}.",
		"",
		"This is independent reviewer ${index + 1}/${reviewers.length}. Your critique must be useful even if other reviewers fail.",
		"${sharedContract}",
		"",
		"Plan:",
		"${plan}`,",
		"    tools: [\"read\", \"grep\", \"find\", \"ls\"],",
		"    agentType: \"reviewer\",",
		"    timeoutMs: input?.agentTimeoutMs ?? ctx.limits.agentTimeoutMs,",
		"  })), {",
		"    concurrency,",
		"    settle: true,",
		"  });",
		"",
		"  const completedCritiques = critiques.filter(Boolean);",
		"  const failed = critiques.length - completedCritiques.length;",
		"  await ctx.log(\"adversarial review fan-out complete\", { total: critiques.length, completed: completedCritiques.length, failed });",
		"  await ctx.writeArtifact(\"critiques.json\", critiques);",
		"",
		"  const synthesis = await ctx.agent(",
		"    `Synthesize these critiques into a revised implementation plan.",
		"",
		"Pattern: synthesis-as-judge. Deduplicate, resolve contradictions, discard unsupported claims unless marked speculative, and preserve accepted risks. Mention failed/empty reviewers explicitly.",
		"",
		"Coverage:",
		"- Reviewers requested: ${reviewers.length}",
		"- Completed reviewers: ${completedCritiques.length}",
		"- Failed/empty reviewers: ${failed}",
		"",
		"Output format:",
		"1. Revised plan in order.",
		"2. Must-fix changes before implementation.",
		"3. Optional/deferred changes.",
		"4. Risks accepted and why.",
		"5. Validation checklist.",
		"6. Coverage gaps / failed reviewers.",
		"",
		"Critiques:",
		"${ctx.compact(completedCritiques, 60000)}`,",
		"    { name: \"plan-synthesis\", tools: [\"read\", \"grep\", \"find\", \"ls\"], agentType: \"planner\", timeoutMs: input?.agentTimeoutMs ?? ctx.limits.agentTimeoutMs },",
		"  );",
		"",
		"  await ctx.writeArtifact(\"revised-plan.md\", synthesis.output);",
		"  return synthesis.output;",
		"};",
		"",
	].join("\n"),
};

EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["classify-and-act"] = EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["scout-fanout"];
EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["fan-out-and-synthesize"] = WORKFLOW_TEMPLATE;
EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["adversarial-verification"] = EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["adversarial-verify"];
EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["generate-and-filter"] = EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["judge-escalate"];
EMBEDDED_WORKFLOW_PATTERN_TEMPLATES.tournaments = EMBEDDED_WORKFLOW_PATTERN_TEMPLATES.tournament;
EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["loop-until-done"] = EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["loop-until-dry"];
EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["compose-verify-claims"] = EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["composition-driver"];
EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["lib-verify-claims"] = EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["verify-claims-lib"];
EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["bug-hunt-repo-audit"] = EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["repo-bug-hunt"];
EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["large-migration"] = EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["scout-fanout"];
EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["plan-review"] = EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["adversarial-plan-review"];
EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["claim-bug-verification"] = EMBEDDED_WORKFLOW_PATTERN_TEMPLATES["adversarial-verify"];

function normalizePatternKey(key: string): string {
	return key.trim().toLowerCase().replace(/^adaptive-/, "").replace(/\.(js|mjs|cjs)$/i, "");
}

export function resolveWorkflowPattern(key: string | undefined): WorkflowPattern | undefined {
	if (!key) return undefined;
	const normalized = normalizePatternKey(key);
	return WORKFLOW_PATTERN_CATALOG.find((pattern) => pattern.key === normalized);
}

export function getPatternUseCases(pattern: WorkflowPattern): string[] {
	return pattern.useCases ?? WORKFLOW_PATTERN_USE_CASES[pattern.key] ?? [];
}

export function formatWorkflowPatternCatalog(patterns = WORKFLOW_PATTERN_CATALOG): string {
	const lines = [
		"Workflow pattern catalog",
		"Use in TUI: /workflows → Patterns tab, then Enter/n to create a project workflow draft.",
		"Use from command line: /workflow new <name> --pattern=<key>",
		"Use from tool: dynamic_workflow action=template name=<key>",
		"",
	];
	const sections: Array<[WorkflowPattern["category"], string]> = [
		["template", "Templates"],
		["compose", "Compose templates"],
		["use-case", "Use-case templates"],
	];
	for (const [category, label] of sections) {
		const sectionPatterns = patterns.filter((pattern) => (pattern.category ?? "template") === category);
		if (sectionPatterns.length === 0) continue;
		lines.push(`## ${label}`, "");
		for (const pattern of sectionPatterns) {
			const useCases = getPatternUseCases(pattern);
			lines.push(`- ${pattern.key} — ${pattern.title}`);
			lines.push(`  ${pattern.blurb}`);
			lines.push(`  When: ${pattern.useWhen}`);
			if (useCases.length) lines.push(`  Use cases: ${useCases.slice(0, 3).join("; ")}`);
			lines.push(`  Input: ${pattern.inputHint}`);
			lines.push(`  Primitives: ${pattern.primitives.join(", ")}`);
		}
		lines.push("");
	}
	lines.push(
		"## Research-backed templates",
		"",
		"Map common agent papers/frameworks to Pi workflow design:",
		"",
		"- **ReAct** -> scout/observe with tools before fan-out; keep reasoning tied to evidence.",
		"- **Self-consistency** -> sample independent branches, then select by consistency/evidence rather than trusting one path.",
		"- **Reflexion / Self-Refine** -> generate -> critique -> refine loops, always bounded by rounds, quiet stops, `maxAgents`, and timeout.",
		"- **Tree of Thoughts** -> branch alternatives, evaluate/prune with a judge, then commit to one path.",
		"- **Multiagent debate** -> adversarial reviewers plus synthesis-as-judge; unsupported claims are dropped.",
		"- **AutoGen / CAMEL / MetaGPT** -> explicit roles, stable artifacts, and clear handoff contracts.",
		"- **SWE-agent / DSPy** -> interface and contracts matter: narrow tools, schemas/fixed formats, and reproducible checks.",
		"",
		"Use these as patterns, not ceremony: every branch needs a reason, a contract, and a stop condition.",
	);
	return lines.join("\n").trimEnd();
}

export function formatWorkflowPatternPromptCheatSheet(patterns = WORKFLOW_PATTERN_CATALOG): string {
	const lines = [
		"Workflow template catalog (choose from these before writing from scratch; inspect with dynamic_workflow action=template, fetch a scaffold with name=<key>):",
	];
	for (const pattern of patterns) {
		lines.push(`- ${pattern.key}: ${pattern.useWhen} Primitives: ${pattern.primitives.join(", ")}.`);
	}
	return lines.join("\n");
}

export function formatWorkflowCompositionPromptGuidance(): string {
	return [
		"Workflow composition rules:",
		"- Use ctx.workflow(\"lib/<name>\", args) for a reusable sub-step with no human/agent decision gate between parent and child; keep one shared run, concurrency pool, maxAgents budget, abort signal, runDir, and resume/cache journal.",
		"- Store reusable contracts under lib/<name>.js, accept one args object, validate inputs, return stable JSON-serializable results, and document the contract in a header comment.",
		"- Depth is 1: a sub-workflow must not call ctx.workflow() again; if the next phase depends on inspecting child output, run separate workflows sequentially and inspect artifacts between runs.",
		"- Prefer compose-verify-claims plus lib-verify-claims as the reference pattern for discovery -> reusable verification; graph literal ctx.workflow(\"...\") calls when reviewing structure.",
	].join("\n");
}

export function formatWorkflowPatternKeyList(patterns = WORKFLOW_PATTERN_CATALOG): string {
	const keys = patterns.map((pattern) => pattern.key).join(", ");
	return `Workflow templates: ${keys}. Inspect details with dynamic_workflow action=template; fetch a scaffold with name=<key>.`;
}

export function formatWorkflowCompositionPromptSummary(): string {
	return "Composition: use ctx.workflow(\"lib/<name>\", args) only for reusable sub-steps with no decision gate; depth is 1; inspect child output in a separate workflow run before changing course.";
}

export async function loadWorkflowPatternCode(pattern: WorkflowPattern): Promise<string> {
	const template = EMBEDDED_WORKFLOW_PATTERN_TEMPLATES[pattern.key];
	if (template === undefined) {
		throw new Error(`Embedded workflow template missing for pattern ${pattern.key}`);
	}
	return template;
}

// An embedded scaffold is only reachable when a catalog pattern's key maps to its code
// (directly or via the alias assignments above). Any embedded scaffold served by no catalog
// pattern is dead code; this invariant keeps new orphans from creeping in.
export function listOrphanedTemplateKeys(): string[] {
	const reachable = new Set<string>();
	for (const pattern of WORKFLOW_PATTERN_CATALOG) {
		const code = EMBEDDED_WORKFLOW_PATTERN_TEMPLATES[pattern.key];
		if (code !== undefined) reachable.add(code);
	}
	return Object.entries(EMBEDDED_WORKFLOW_PATTERN_TEMPLATES)
		.filter(([, code]) => !reachable.has(code))
		.map(([key]) => key)
		.sort();
}
