// Tests unitarios para scripts/sync-personas-readme.mjs — mirror legible y commiteado de las
// personas del proyecto. Contrato: render puro (renderPersonasReadme) + loader (loadPersonas)
// + una sync end-to-end sobre un árbol temporal (writes idempotentes y --check sin escritura).
import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const SCRIPT = path.join(REPO, "scripts", "sync-personas-readme.mjs");
const { formatPersonasReadme, renderPersonasReadme, renderPromptMarkdown, loadPersonas, syncPersonasReadme } =
	await import(pathToFileURL(SCRIPT).href);

const persona = (over = {}) => ({
	tools: ["read", "grep", "find", "ls"],
	thinking: "high",
	systemPrompt: "Act as a test advisor. ".repeat(3).trim(),
	appendSystemPrompt: "When advising, be terse. ".repeat(3).trim(),
	...over,
});

test("renderPersonasReadme renders header, meta, and prompts verbatim in name order", () => {
	const md = renderPersonasReadme([
		{ name: "alpha", data: persona() },
		{ name: "beta", data: persona({ systemPrompt: "Beta identity prompt." }) },
	]);
	// El marker GENERATED y el puntero a la fuente de verdad van primero.
	assert.match(md, /^<!-- GENERATED by scripts\/sync-personas-readme\.mjs/);
	assert.match(md, /npm run sync:personas/);
	// Secciones en orden por nombre.
	assert.ok(md.indexOf("## alpha") < md.indexOf("## beta"));
	// Se renderizan las meta keys; las prompt keys quedan fuera de la lista meta.
	assert.match(md, /- \*\*thinking\*\*: `"high"`/);
	assert.match(md, /- \*\*tools\*\*: `\["read","grep","find","ls"\]`/);
	assert.doesNotMatch(md, /- \*\*systemPrompt\*\*/);
	// Los prompts van verbatim bajo sus propios headings, con conteo de chars.
	assert.match(md, /### systemPrompt \(\d+ chars\)\n\nBeta identity prompt\./);
	assert.match(md, /### appendSystemPrompt \(\d+ chars\)/);
	// Newline final determinista.
	assert.ok(md.endsWith("\n"));
});

test("formatPersonasReadme applies the repository Markdown style", async () => {
	const md = await formatPersonasReadme([
		{ name: "alpha", data: persona() },
		{ name: "beta", data: persona({ skills: ["a-skill"] }) },
	]);
	assert.doesNotMatch(md, /^\| --- \|/mu);
	assert.match(md, /^\| -+ \|/mu);
});

test("renderPromptMarkdown turns (N) markers into an ordered list with bolded leads", () => {
	const text =
		"Do the frame: (1) Fear check — name it. (2) Step — keep it green; commit. Name and refuse: dogma. Keep it lean.";
	const md = renderPromptMarkdown(text);
	assert.match(md, /^Do the frame:$/m);
	assert.match(md, /^1\. \*\*Fear check\*\* — name it\.$/m);
	assert.match(md, /^2\. \*\*Step\*\* — keep it green; commit\.$/m);
	// La prosa sobrante después del último item pasa a párrafos, no a contenido de lista.
	assert.match(md, /^Name and refuse: dogma\.$/m);
	assert.match(md, /^Keep it lean\.$/m);
});

test("renderPromptMarkdown keeps prose as sentence paragraphs, guarding abbreviations and questions", () => {
	const text = "First idea. Second idea holds, e.g. this case stays. What now? Still same paragraph.";
	assert.equal(
		renderPromptMarkdown(text),
		"First idea.\n\nSecond idea holds, e.g. this case stays.\n\nWhat now? Still same paragraph.",
	);
});

test("renderPromptMarkdown leaves non-checklist parenthesised numbers alone", () => {
	assert.equal(
		renderPromptMarkdown("See item (3) in the appendix. Next sentence."),
		"See item (3) in the appendix.\n\nNext sentence.",
	);
});

test("renderPromptMarkdown wraps prose at 120 characters without losing words", () => {
	const source = `${"A descriptive phrase with several words ".repeat(8)}without an earlier sentence boundary.`;
	const rendered = renderPromptMarkdown(source);
	assert.ok(rendered.split("\n").every((line) => line.length <= 120));
	assert.equal(collapse(rendered), collapse(source));
});

// El mirror debe seguir VERBATIM: quitar del prompt renderizado el andamiaje Markdown (markers de lista,
// bold, saltos de párrafo) debe reconstruir el string fuente.
const reconstruct = (md) =>
	md
		.split("\n")
		.map((l) => l.replace(/^(\d+)\. /, "($1) "))
		.filter((l) => l.trim() !== "")
		.join(" ")
		.replace(/\*\*/g, "")
		.replace(/\s+/g, " ")
		.trim();
const collapse = (s) => s.replace(/\s+/g, " ").trim();

test("renderPromptMarkdown is lossless over the real committed personas", () => {
	const dir = path.join(REPO, ".pi", "personas");
	for (const { name, data } of loadPersonas(dir)) {
		for (const key of ["systemPrompt", "appendSystemPrompt"]) {
			if (typeof data[key] !== "string") continue;
			assert.equal(reconstruct(renderPromptMarkdown(data[key])), collapse(data[key]), `${name}.${key} not verbatim`);
		}
	}
});

test("renderPersonasReadme includes a linked index table and separators", () => {
	const md = renderPersonasReadme([
		{ name: "alpha", data: persona() },
		{ name: "beta", data: persona({ skills: ["a-skill"] }) },
	]);
	assert.match(md, /\| Persona \| thinking \| skills \| prompts \|/);
	assert.match(md, /\| \[alpha\]\(#alpha\) \| high \| — \| \d+ \+ \d+ chars \|/);
	assert.match(md, /\| \[beta\]\(#beta\) \| high \| a-skill \| \d+ \+ \d+ chars \|/);
	assert.match(md, /\n---\n/);
});

test("renderPersonasReadme notes an empty persona set", () => {
	assert.match(renderPersonasReadme([]), /_No personas defined\._/);
});

test("renderPersonasReadme moves long metadata to a fenced block", () => {
	const md = renderPersonasReadme([
		{ name: "alpha", data: persona({ tools: Array.from({ length: 30 }, (_, index) => `tool-${index}`) }) },
	]);
	assert.match(md, /- \*\*tools\*\*:\n\n {2}```json/);
});

test("loadPersonas reads *.json sorted by name and ignores other files", () => {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), "personas-load-"));
	try {
		fs.writeFileSync(path.join(root, "zed.json"), JSON.stringify(persona()));
		fs.writeFileSync(path.join(root, "abe.json"), JSON.stringify(persona()));
		fs.writeFileSync(path.join(root, "README.md"), "not a persona");
		const loaded = loadPersonas(root);
		assert.deepEqual(
			loaded.map((p) => p.name),
			["abe", "zed"],
		);
		assert.equal(loaded[0].data.thinking, "high");
		assert.deepEqual(loadPersonas(path.join(root, "missing")), []);
	} finally {
		fs.rmSync(root, { recursive: true, force: true });
	}
});

test("syncPersonasReadme writes MD + HTML mirrors, is idempotent, and check never writes", async () => {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), "personas-sync-"));
	try {
		const dir = path.join(root, ".pi", "personas");
		fs.mkdirSync(dir, { recursive: true });
		fs.writeFileSync(path.join(dir, "solo.json"), JSON.stringify(persona()));
		const readme = path.join(dir, "README.md");
		const html = path.join(dir, "README.html");

		// La primera pasada escribe ambos mirrors; la segunda es un no-op.
		assert.equal((await syncPersonasReadme(root, {})).changed, true);
		assert.ok(fs.existsSync(readme));
		assert.ok(fs.existsSync(html));
		const rendered = fs.readFileSync(html, "utf8");
		assert.match(rendered, /^<!doctype html>/);
		// El H1 cae en el header de pandi (los comentarios GENERATED del inicio se quitan antes del render).
		assert.match(rendered, /<h1>Project personas<\/h1>/);
		assert.match(rendered, /solo/);
		assert.equal((await syncPersonasReadme(root, {})).changed, false);

		// Una edición manual en cualquiera de los mirrors genera drift: check la reporta SIN escribir; sync la restaura.
		fs.writeFileSync(readme, "hand-edited\n");
		assert.equal((await syncPersonasReadme(root, { check: true })).changed, true);
		assert.equal(fs.readFileSync(readme, "utf8"), "hand-edited\n");
		assert.equal((await syncPersonasReadme(root, {})).changed, true);
		assert.match(fs.readFileSync(readme, "utf8"), /## solo/);
		fs.writeFileSync(html, "<!doctype html>hand-edited");
		assert.equal((await syncPersonasReadme(root, { check: true })).changed, true);
		assert.equal(fs.readFileSync(html, "utf8"), "<!doctype html>hand-edited");
		assert.equal((await syncPersonasReadme(root, {})).changed, true);
		assert.match(fs.readFileSync(html, "utf8"), /<h1>Project personas<\/h1>/);
	} finally {
		fs.rmSync(root, { recursive: true, force: true });
	}
});
