// Unit tests for scripts/sync-personas-readme.mjs — committed readable mirror of the
// project personas. Contract: pure render (renderPersonasReadme) + loader (loadPersonas)
// + an end-to-end sync over a temp tree (idempotent writes, non-writing --check).
import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const SCRIPT = path.join(REPO, "scripts", "sync-personas-readme.mjs");
const { renderPersonasReadme, renderPromptMarkdown, loadPersonas, syncPersonasReadme } = await import(
	pathToFileURL(SCRIPT).href
);

const persona = (over = {}) => ({
	tools: ["read", "grep", "find", "ls"],
	thinking: "high",
	systemPrompt: "Act as a test advisor. ".repeat(3).trim(),
	appendSystemPrompt: "When advising, be terse. ".repeat(3).trim(),
	...over,
});

test("renderPersonasReadme renders header, meta, and prompts verbatim in name order", () => {
	const md = renderPersonasReadme([
		{ name: "alpha", data: persona() },
		{ name: "beta", data: persona({ systemPrompt: "Beta identity prompt." }) },
	]);
	// Generated marker + source-of-truth pointer come first.
	assert.match(md, /^<!-- GENERATED by scripts\/sync-personas-readme\.mjs/);
	assert.match(md, /npm run sync:personas/);
	// Sections in name order.
	assert.ok(md.indexOf("## alpha") < md.indexOf("## beta"));
	// Meta keys rendered, prompt keys excluded from the meta list.
	assert.match(md, /- \*\*thinking\*\*: `"high"`/);
	assert.match(md, /- \*\*tools\*\*: `\["read","grep","find","ls"\]`/);
	assert.doesNotMatch(md, /- \*\*systemPrompt\*\*/);
	// Prompts verbatim under their own headings, with char counts.
	assert.match(md, /### systemPrompt \(\d+ chars\)\n\nBeta identity prompt\./);
	assert.match(md, /### appendSystemPrompt \(\d+ chars\)/);
	// Deterministic trailing newline.
	assert.ok(md.endsWith("\n"));
});

test("renderPromptMarkdown turns (N) markers into an ordered list with bolded leads", () => {
	const text =
		"Do the frame: (1) Fear check — name it. (2) Step — keep it green; commit. Name and refuse: dogma. Keep it lean.";
	const md = renderPromptMarkdown(text);
	assert.match(md, /^Do the frame:$/m);
	assert.match(md, /^1\. \*\*Fear check\*\* — name it\.$/m);
	assert.match(md, /^2\. \*\*Step\*\* — keep it green; commit\.$/m);
	// Overflow prose after the last item becomes paragraphs, not list content.
	assert.match(md, /^Name and refuse: dogma\.$/m);
	assert.match(md, /^Keep it lean\.$/m);
});

test("renderPromptMarkdown keeps prose as sentence paragraphs, guarding abbreviations and questions", () => {
	const text = "First idea. Second idea holds, e.g. this case stays. What now? Still same paragraph.";
	assert.equal(
		renderPromptMarkdown(text),
		"First idea.\n\nSecond idea holds, e.g. this case stays.\n\nWhat now? Still same paragraph.",
	);
});

test("renderPromptMarkdown leaves non-checklist parenthesised numbers alone", () => {
	assert.equal(
		renderPromptMarkdown("See item (3) in the appendix. Next sentence."),
		"See item (3) in the appendix.\n\nNext sentence.",
	);
});

// The mirror must stay VERBATIM: stripping the markdown scaffolding (list markers,
// bold, paragraph breaks) from the rendered prompt must reconstruct the source string.
const reconstruct = (md) =>
	md
		.split("\n")
		.map((l) => l.replace(/^(\d+)\. /, "($1) "))
		.filter((l) => l.trim() !== "")
		.join(" ")
		.replace(/\*\*/g, "")
		.replace(/\s+/g, " ")
		.trim();
const collapse = (s) => s.replace(/\s+/g, " ").trim();

test("renderPromptMarkdown is lossless over the real committed personas", () => {
	const dir = path.join(REPO, ".pi", "personas");
	for (const { name, data } of loadPersonas(dir)) {
		for (const key of ["systemPrompt", "appendSystemPrompt"]) {
			if (typeof data[key] !== "string") continue;
			assert.equal(reconstruct(renderPromptMarkdown(data[key])), collapse(data[key]), `${name}.${key} not verbatim`);
		}
	}
});

test("renderPersonasReadme includes a linked index table and separators", () => {
	const md = renderPersonasReadme([
		{ name: "alpha", data: persona() },
		{ name: "beta", data: persona({ skills: ["a-skill"] }) },
	]);
	assert.match(md, /\| Persona \| thinking \| skills \| prompts \|/);
	assert.match(md, /\| \[alpha\]\(#alpha\) \| high \| — \| \d+ \+ \d+ chars \|/);
	assert.match(md, /\| \[beta\]\(#beta\) \| high \| a-skill \| \d+ \+ \d+ chars \|/);
	assert.match(md, /\n---\n/);
});

test("renderPersonasReadme notes an empty persona set", () => {
	assert.match(renderPersonasReadme([]), /_No personas defined\._/);
});

test("loadPersonas reads *.json sorted by name and ignores other files", () => {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), "personas-load-"));
	try {
		fs.writeFileSync(path.join(root, "zed.json"), JSON.stringify(persona()));
		fs.writeFileSync(path.join(root, "abe.json"), JSON.stringify(persona()));
		fs.writeFileSync(path.join(root, "README.md"), "not a persona");
		const loaded = loadPersonas(root);
		assert.deepEqual(
			loaded.map((p) => p.name),
			["abe", "zed"],
		);
		assert.equal(loaded[0].data.thinking, "high");
		assert.deepEqual(loadPersonas(path.join(root, "missing")), []);
	} finally {
		fs.rmSync(root, { recursive: true, force: true });
	}
});

test("syncPersonasReadme writes MD + HTML mirrors, is idempotent, and check never writes", () => {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), "personas-sync-"));
	try {
		const dir = path.join(root, ".pi", "personas");
		fs.mkdirSync(dir, { recursive: true });
		fs.writeFileSync(path.join(dir, "solo.json"), JSON.stringify(persona()));
		const readme = path.join(dir, "README.md");
		const html = path.join(dir, "README.html");

		// First pass writes both mirrors; second pass is a no-op.
		assert.equal(syncPersonasReadme(root, {}).changed, true);
		assert.ok(fs.existsSync(readme));
		assert.ok(fs.existsSync(html));
		const rendered = fs.readFileSync(html, "utf8");
		assert.match(rendered, /^<!doctype html>/);
		// The H1 lands in the pandi header (leading GENERATED comments stripped pre-render).
		assert.match(rendered, /<h1>Project personas<\/h1>/);
		assert.match(rendered, /solo/);
		assert.equal(syncPersonasReadme(root, {}).changed, false);

		// Hand-edit on either mirror drifts: check reports it WITHOUT writing; sync restores.
		fs.writeFileSync(readme, "hand-edited\n");
		assert.equal(syncPersonasReadme(root, { check: true }).changed, true);
		assert.equal(fs.readFileSync(readme, "utf8"), "hand-edited\n");
		assert.equal(syncPersonasReadme(root, {}).changed, true);
		assert.match(fs.readFileSync(readme, "utf8"), /## solo/);
		fs.writeFileSync(html, "<!doctype html>hand-edited");
		assert.equal(syncPersonasReadme(root, { check: true }).changed, true);
		assert.equal(fs.readFileSync(html, "utf8"), "<!doctype html>hand-edited");
		assert.equal(syncPersonasReadme(root, {}).changed, true);
		assert.match(fs.readFileSync(html, "utf8"), /<h1>Project personas<\/h1>/);
	} finally {
		fs.rmSync(root, { recursive: true, force: true });
	}
});
