import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { test } from "node:test";
import {
	buildClaudeWorkflowsReadme,
	buildClaudeWorkflowsSkillReadme,
	buildScaffoldCatalog,
	catalogPaths,
	expectedOutputs,
	extractCanonicalBody,
	parseCheckOnly,
	syncScaffoldCatalog,
} from "../../sync-scaffold-catalog.mjs";

function logs() {
	const lines = [];
	return { lines, log: (line) => lines.push(line), error: (line) => lines.push(line) };
}

const SAMPLE_BODY = `> **Regla de oro: empezá simple.**

## 1. Inicio rápido
`;

test("sync-scaffold-catalog helpers expose check mode and catalog paths", () => {
	assert.equal(parseCheckOnly(["--check"]), true);
	assert.equal(parseCheckOnly([]), false);
	assert.ok(catalogPaths("/repo").canonical.endsWith("catalog-prose.es.md"));
});

test("extractCanonicalBody strips the editable-source HTML banner", () => {
	const raw = `<!-- fuente canónica -->\n\n${SAMPLE_BODY}`;
	assert.equal(extractCanonicalBody(raw), SAMPLE_BODY);
});

test("expectedOutputs builds three variant headers over the same body", () => {
	const out = expectedOutputs(SAMPLE_BODY);
	assert.ok(out.claudeWorkflowsReadme.includes("GENERATED by scripts/sync-scaffold-catalog.mjs"));
	assert.ok(out.scaffoldCatalog.includes("**Qué es esto.**"));
	assert.ok(out.claudeWorkflowsSkillReadme.includes("**Procedencia.**"));
	assert.ok(out.claudeWorkflowsSkillReadme.includes("**Qué son.**"));
	assert.ok(out.claudeWorkflowsReadme.endsWith(SAMPLE_BODY));
	assert.ok(out.scaffoldCatalog.endsWith(SAMPLE_BODY));
	assert.ok(out.claudeWorkflowsSkillReadme.endsWith(SAMPLE_BODY));
	assert.equal(buildClaudeWorkflowsReadme(SAMPLE_BODY), buildScaffoldCatalog(SAMPLE_BODY));
	assert.notEqual(buildClaudeWorkflowsReadme(SAMPLE_BODY), buildClaudeWorkflowsSkillReadme(SAMPLE_BODY));
});

test("syncScaffoldCatalog writes three destinations from canonical prose", async () => {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), "scaffold-catalog-"));
	try {
		const paths = catalogPaths(root);
		fs.mkdirSync(path.dirname(paths.canonical), { recursive: true });
		fs.mkdirSync(path.dirname(paths.claudeWorkflowsSkillReadme), { recursive: true });
		fs.mkdirSync(path.dirname(paths.claudeWorkflowsReadme), { recursive: true });
		fs.writeFileSync(paths.canonical, `<!-- canonical -->\n\n${SAMPLE_BODY}`);

		const writeLog = logs();
		assert.deepEqual(await syncScaffoldCatalog({ paths, log: writeLog.log, error: writeLog.error }), {
			ok: true,
			wrote: true,
			drift: false,
			missing: false,
		});
		const want = expectedOutputs(SAMPLE_BODY);
		assert.equal(fs.readFileSync(paths.claudeWorkflowsReadme, "utf8"), want.claudeWorkflowsReadme);
		assert.equal(fs.readFileSync(paths.scaffoldCatalog, "utf8"), want.scaffoldCatalog);
		assert.equal(fs.readFileSync(paths.claudeWorkflowsSkillReadme, "utf8"), want.claudeWorkflowsSkillReadme);

		const checkLog = logs();
		assert.deepEqual(
			await syncScaffoldCatalog({ checkOnly: true, paths, log: checkLog.log, error: checkLog.error }),
			{
				ok: true,
				wrote: false,
				drift: false,
				missing: false,
				driftCount: 0,
			},
		);
	} finally {
		fs.rmSync(root, { recursive: true, force: true });
	}
});

test("syncScaffoldCatalog reports check-mode drift without writing", async () => {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), "scaffold-catalog-"));
	try {
		const paths = catalogPaths(root);
		fs.mkdirSync(path.dirname(paths.canonical), { recursive: true });
		fs.mkdirSync(path.dirname(paths.claudeWorkflowsReadme), { recursive: true });
		fs.writeFileSync(paths.canonical, SAMPLE_BODY);
		fs.writeFileSync(paths.claudeWorkflowsReadme, "# stale\n");

		const captured = logs();
		assert.deepEqual(
			await syncScaffoldCatalog({ checkOnly: true, paths, log: captured.log, error: captured.error }),
			{
				ok: false,
				wrote: false,
				drift: true,
				missing: false,
				driftCount: 3,
			},
		);
		assert.equal(fs.readFileSync(paths.claudeWorkflowsReadme, "utf8"), "# stale\n");
		assert.match(captured.lines.join("\n"), /drift/);
	} finally {
		fs.rmSync(root, { recursive: true, force: true });
	}
});

test("syncScaffoldCatalog reports missing canonical source", async () => {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), "scaffold-catalog-"));
	try {
		const captured = logs();
		assert.deepEqual(
			await syncScaffoldCatalog({
				paths: catalogPaths(root),
				log: captured.log,
				error: captured.error,
			}),
			{ ok: false, wrote: false, drift: false, missing: true },
		);
		assert.match(captured.lines.join("\n"), /missing canonical/);
	} finally {
		fs.rmSync(root, { recursive: true, force: true });
	}
});
