// Unit tests for scripts/sync-personas-readme.mjs — committed readable mirror of the
// project personas. Contract: pure render (renderPersonasReadme) + loader (loadPersonas)
// + an end-to-end sync over a temp tree (idempotent writes, non-writing --check).
import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { test } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const SCRIPT = path.join(REPO, "scripts", "sync-personas-readme.mjs");
const { renderPersonasReadme, loadPersonas, syncPersonasReadme } = await import(pathToFileURL(SCRIPT).href);

const persona = (over = {}) => ({
	tools: ["read", "grep", "find", "ls"],
	thinking: "high",
	systemPrompt: "Act as a test advisor. ".repeat(3).trim(),
	appendSystemPrompt: "When advising, be terse. ".repeat(3).trim(),
	...over,
});

test("renderPersonasReadme renders header, meta, and prompts verbatim in name order", () => {
	const md = renderPersonasReadme([
		{ name: "alpha", data: persona() },
		{ name: "beta", data: persona({ systemPrompt: "Beta identity prompt." }) },
	]);
	// Generated marker + source-of-truth pointer come first.
	assert.match(md, /^<!-- GENERATED by scripts\/sync-personas-readme\.mjs/);
	assert.match(md, /npm run sync:personas/);
	// Sections in name order.
	assert.ok(md.indexOf("## alpha") < md.indexOf("## beta"));
	// Meta keys rendered, prompt keys excluded from the meta list.
	assert.match(md, /- \*\*thinking\*\*: `"high"`/);
	assert.match(md, /- \*\*tools\*\*: `\["read","grep","find","ls"\]`/);
	assert.doesNotMatch(md, /- \*\*systemPrompt\*\*/);
	// Prompts verbatim under their own headings, with char counts.
	assert.match(md, /### systemPrompt \(\d+ chars\)\n\nBeta identity prompt\./);
	assert.match(md, /### appendSystemPrompt \(\d+ chars\)/);
	// Deterministic trailing newline.
	assert.ok(md.endsWith("\n"));
});

test("renderPersonasReadme notes an empty persona set", () => {
	assert.match(renderPersonasReadme([]), /_No personas defined\._/);
});

test("loadPersonas reads *.json sorted by name and ignores other files", () => {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), "personas-load-"));
	try {
		fs.writeFileSync(path.join(root, "zed.json"), JSON.stringify(persona()));
		fs.writeFileSync(path.join(root, "abe.json"), JSON.stringify(persona()));
		fs.writeFileSync(path.join(root, "README.md"), "not a persona");
		const loaded = loadPersonas(root);
		assert.deepEqual(
			loaded.map((p) => p.name),
			["abe", "zed"],
		);
		assert.equal(loaded[0].data.thinking, "high");
		assert.deepEqual(loadPersonas(path.join(root, "missing")), []);
	} finally {
		fs.rmSync(root, { recursive: true, force: true });
	}
});

test("syncPersonasReadme writes the mirror, is idempotent, and check never writes", () => {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), "personas-sync-"));
	try {
		const dir = path.join(root, ".pi", "personas");
		fs.mkdirSync(dir, { recursive: true });
		fs.writeFileSync(path.join(dir, "solo.json"), JSON.stringify(persona()));
		const readme = path.join(dir, "README.md");

		// First pass writes; second pass is a no-op.
		assert.equal(syncPersonasReadme(root, {}).changed, true);
		assert.ok(fs.existsSync(readme));
		assert.equal(syncPersonasReadme(root, {}).changed, false);

		// Hand-edit drifts: check reports it WITHOUT writing; sync restores.
		fs.writeFileSync(readme, "hand-edited\n");
		assert.equal(syncPersonasReadme(root, { check: true }).changed, true);
		assert.equal(fs.readFileSync(readme, "utf8"), "hand-edited\n");
		assert.equal(syncPersonasReadme(root, {}).changed, true);
		assert.match(fs.readFileSync(readme, "utf8"), /## solo/);
	} finally {
		fs.rmSync(root, { recursive: true, force: true });
	}
});
